###register request
post http://localhost:3000/auth/register
Content-Type: application/json

{
    "username" : "pdrmsfr1256",
    "email" : "pedram1256@gmail.com",
    "mobile" : "09125065233",
    "password" : "12345678",
    "confrim_password" : "12345678"
}


###login request
post http://localhost:3000/auth/login
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
    "username" : "pdrmsfr",
    "password" : "12345678"
}
